export const artes = [
  {
    "Arte Name": "Slicing Foot\n鋭武\nEimu",
    "Elemental Attributes": "Non‑Elemental",
    "Additional Effects": "Stun (40)",
    "Enemy Race": "-",
    "Base Power": 100,
    "Max Hits": 1,
    "SG Cost": 5,
    Level: "default",
    Requirements: "-",
  },
  {
    "Arte Name": "Tearing Thorn\n裂棘\nResshi",
    "Elemental Attributes": "Earth",
    "Additional Effects": "Stun (36)",
    "Enemy Race": "-",
    "Base Power": 95,
    "Max Hits": 1,
    "SG Cost": 6,
    Level: "default",
    Requirements: "-",
  },
  {
    "Arte Name": "Gouging Spin\n円抉\nEnketsu",
    "Elemental Attributes": "Non‑Elemental",
    "Additional Effects": "Stun (60)",
    "Enemy Race": "Crustacean",
    "Base Power": 125,
    "Max Hits": 2,
    "SG Cost": 8,
    Level: "default",
    Requirements: "-",
  },
  {
    "Arte Name": "Swallow Dance\n飛燕連脚\nHienrenkyaku",
    "Elemental Attributes": "Wind",
    "Additional Effects": "Stun (50)",
    "Enemy Race": "Winged",
    "Base Power": 175,
    "Max Hits": 2,
    "SG Cost": 11,
    Level: "6",
    Requirements: "-",
  },
  {
    "Arte Name": "Twin Whip\n双幻脚\nSougenkyaku",
    "Elemental Attributes": "Water",
    "Additional Effects": "P.ATK Down (20%)\nStun (15)",
    "Enemy Race": "Amorphous",
    "Base Power": 195,
    "Max Hits": 3,
    "SG Cost": 13,
    Level: "10",
    Requirements: "-",
  },
  {
    "Arte Name": "Avalanche Fang\n崩牙襲\nHougashuu",
    "Elemental Attributes": "Earth",
    "Additional Effects": "HP Drain (20%)",
    "Enemy Race": "-",
    "Base Power": 225,
    "Max Hits": 3,
    "SG Cost": 15,
    Level: "15",
    Requirements: "-",
  },
  {
    "Arte Name": "Harsh Rebuttal\n説破\nSeppa",
    "Elemental Attributes": "Non‑Elemental",
    "Additional Effects": "Stun (60)",
    "Enemy Race": "Demihuman",
    "Base Power": 200,
    "Max Hits": 3,
    "SG Cost": 11,
    Level: "default",
    Requirements: "-",
  },
  {
    "Arte Name": "Water Snake's Wake\n水蛇葬\nSuijasou",
    "Elemental Attributes": "Water",
    "Additional Effects": "Stun (65)",
    "Enemy Race": "Apodous",
    "Base Power": 230,
    "Max Hits": 3,
    "SG Cost": 16,
    Level: "17",
    Requirements: "-",
  },
  {
    "Arte Name": "Moonlight Cyclone\n旋月華\nTsumujigekka",
    "Elemental Attributes": "Wind",
    "Additional Effects": "HP Drain (25%)",
    "Enemy Race": "Beast",
    "Base Power": 290,
    "Max Hits": 4,
    "SG Cost": 18,
    Level: "21",
    Requirements: "-",
  },
  {
    "Arte Name": "Soaring Dragon\n炎牙昇竜脚\nEnga Shouryuukyaku",
    "Elemental Attributes": "Earth\nFire",
    "Additional Effects": "A.ATK Down (25%)\nStun (20)",
    "Enemy Race": "Dragon",
    "Base Power": 280,
    "Max Hits": 4,
    "SG Cost": 21,
    Level: "27",
    Requirements: "-",
  },
  {
    "Arte Name": "Rising Moon\n真月\nShingetsu",
    "Elemental Attributes": "Non‑Elemental",
    "Additional Effects": "Paralysis (7%)",
    "Enemy Race": "-",
    "Base Power": 170,
    "Max Hits": 3,
    "SG Cost": 9,
    Level: "default",
    Requirements: "-",
  },
  // {
  //   "Arte Name": "Rising Falcon\n飛天翔駆\nHitenshouku",
  //   "Elemental Attributes": "Wind",
  //   "Additional Effects": "Stun (75)",
  //   "Enemy Race": "-",
  //   "Base Power": 310,
  //   "Max Hits": 5,
  //   "SG Cost": 22,
  //   Level: "31",
  //   Requirements: "-",
  // },
  {
    "Arte Name": "Heaven's Wrath\n四葬天幻\nShisoutengen",
    "Elemental Attributes": "Water\nWind",
    "Additional Effects": "Focus Down (30%)\nStun (30)",
    "Enemy Race": "Undead",
    "Base Power": 320,
    "Max Hits": 8,
    "SG Cost": 26,
    Level: "37",
    Requirements: "-",
  },
  {
    "Arte Name": "Infernal Torrent\n魔王炎撃波\nMaou Engekiha",
    "Elemental Attributes": "Fire",
    "Additional Effects": "Burn (7.5%)",
    "Enemy Race": "Fiend",
    "Base Power": 440,
    "Max Hits": 5,
    "SG Cost": 34,
    Level: "41",
    Requirements: "-",
  },
];

export const hiddenArtes = [
  {
    "Arte Name": "Searing Edge\n紅火刃\nKoukajin",
    "Elemental Attributes": "Fire",
    "Additional Effects": "Burn (4.8%)",
    "Enemy Race": "Beast",
    "Base Power": 200,
    "Max Hits": 2,
    "SG Cost": 13,
    Level: "event",
    Requirements: "obtained during the main story",
  },
  {
    "Arte Name": "Mega Sonic Thrust\n空破絶掌撃\nKuuha Zesshougeki",
    "Elemental Attributes": "Earth",
    "Additional Effects": "Slow (4.8%)",
    "Enemy Race": "Armored",
    "Base Power": 290,
    "Max Hits": 3,
    "SG Cost": 22,
    Level: "9",
    Requirements: "-",
  },
  {
    "Arte Name": "Shell Splitter\n裂甲刃\nRekkoujin",
    "Elemental Attributes": "Water",
    "Additional Effects": "Poison (4.8%)",
    "Enemy Race": "Crustacean",
    "Base Power": 270,
    "Max Hits": 5,
    "SG Cost": 24,
    Level: "13",
    Requirements: "-",
  },
  {
    "Arte Name": "Shadow Flow\n陰昴流\nKagesubaru",
    "Elemental Attributes": "Earth\nWind",
    "Additional Effects": "P.DEF Down (24%)\nStun (20)",
    "Enemy Race": "Amorphous",
    "Base Power": 320,
    "Max Hits": 4,
    "SG Cost": 28,
    Level: "19",
    Requirements: "-",
  },
  {
    "Arte Name": "Slag Assault\n岩斬滅砕陣\nGanzan Messaijin",
    "Elemental Attributes": "Earth\nFire",
    "Additional Effects": "Stun (72)",
    "Enemy Race": "Apodous",
    "Base Power": 390,
    "Max Hits": 5,
    "SG Cost": 30,
    Level: "25",
    Requirements: "-",
  },
  {
    "Arte Name": "Grounding Strike\n堕天衝\nDatenshou",
    "Elemental Attributes": "Wind",
    "Additional Effects": "Fatigue (6%)",
    "Enemy Race": "Winged",
    "Base Power": 400,
    "Max Hits": 5,
    "SG Cost": 32,
    Level: "35",
    Requirements: "-",
  },
  {
    "Arte Name": "Cerberus Wave\n灼風狼火\nShappuurouka",
    "Elemental Attributes": "Fire\nWind",
    "Additional Effects": "Stun (90)",
    "Enemy Race": "Demihuman",
    "Base Power": 420,
    "Max Hits": 4,
    "SG Cost": 33,
    Level: "39",
    Requirements: "-",
  },
  {
    "Arte Name": "Banishing Thunder\n邪霊雷牙\nJareiraiga",
    "Elemental Attributes": "Water\nWind",
    "Additional Effects": "A.DEF Down (30%)\nStun (25)",
    "Enemy Race": "Undead",
    "Base Power": 480,
    "Max Hits": 3,
    "SG Cost": 35,
    Level: "43",
    Requirements: "-",
  },
  {
    "Arte Name": "Binding Frost\n縛氷幻霧\nBakuhyougenmu",
    "Elemental Attributes": "Earth\nWater",
    "Additional Effects": "Stun (90)",
    "Enemy Race": "Fiend",
    "Base Power": 500,
    "Max Hits": 5,
    "SG Cost": 40,
    Level: "47",
    Requirements: "-",
  },
  {
    "Arte Name": "Scale Crusher\n割砕竜閃\nKassairyuusen",
    "Elemental Attributes": "Water\nFire",
    "Additional Effects": "Stun (108)",
    "Enemy Race": "Dragon",
    "Base Power": 460,
    "Max Hits": 4,
    "SG Cost": 43,
    Level: "55",
    Requirements: "-",
  },
  {
    "Arte Name": "Defiant Conviction\n無律排反\nMuritsuhahan",
    "Elemental Attributes": "Non‑Elemental",
    "Additional Effects": "Paralysis (9%)",
    "Enemy Race": "Person",
    "Base Power": 600,
    "Max Hits": 8,
    "SG Cost": 52,
    Level: "60",
    Requirements: "-",
  },
];
